- id: cpplint
  name: Compliance with Google C++ Style Guide
  description: Run cpplint against C++ files
  language: python
  types: [c++]
  entry: cpplint
- id: cppcheck
  name: Static analysis of C/C++ code
  description: Run cppcheck against C/C++ files
  language: python
  types: [c, c++]
  entry: cppcheck
