- id: cpplint
  name: Compliance with Google C++ Style Guide
  description: Run cpplint against C++ files
  language: python
  types: [c++]
  entry: cpplint
- id: cppcheck
  name: Static analysis of C/C++ code
  description: Run cppcheck against C/C++ files
  language: system
  files: \.(cpp|cxx|cc|c\+\+|c|tpp|txx)$
  entry: cppcheck
  args: ["--error-exitcode=1"]
